#!/bin/sh

set -e

dev=$1
shift

if [ -z "$dev" ]; then
  echo No device
  exit 1
fi

name=$(basename $dev)
full_sys_path=$(readlink -e /sys/class/tty/$name)

socat -v tcp-l:5555,reuseaddr file:/$dev,nonblock
#,waitlock=/var/run/tty0.lock
#false
