#!/bin/bash

set -e

dev=$1
shift

if [ -z "$dev" ]; then
  echo No device
  exit 1
fi

name=$(basename $dev)

if [ -e /sys/bus/usb-serial/devices/$name ]; then
  full_sys_path=$(readlink -e /sys/bus/usb-serial/devices/$name)
  usb_connection=$(basename $(dirname $full_sys_path)) # eg 1-1.2:1.0
  usb_port=$(echo $usb_connection | cut -d: -f1)
else
  full_sys_path=$(readlink -e /sys/class/tty/$name)
  echo "Can't handle non-USB serial yet: $name"
  exit 2
fi

declare -A conf
# static configuration - we'll move it to a config file one day
conf[1-1.2]=5555
conf[1-1.3]=5556
conf[1-1.4]=5557
conf[1-1.5]=5558

tcp_port=${conf[$usb_port]}
echo "Starting serial service on port $tcp_port for $dev on USB $usb_port"
socat tcp-l:$tcp_port,reuseaddr,fork,max-children=1 file:/$dev,nonblock,b115200,raw,echo=0
